### ISSUE TITLE
CI adds build info of every build to the general build history (P7)

### ISSUE THREAD

**Issue by AmandaStromdahl** [PersonligaPersson/DD2480_Group_27_CI#12]
Every time the CI builds the program, the build info should be added to the complete build history, that can be accessed through a URL. This information needs to persist even if the CI server were to be restarted.

**Comment by PersonligaPersson** [comment]
Overlaps with issue #11 . The loggfiles are persistent.

**Comment by PersonligaPersson** [comment]
As this overlaps with issue #11 and #11 is closed I will close this issue.
