### ISSUE TITLE
Evaluate github's webhook service

### ISSUE THREAD

**Issue by PersonligaPersson** [PersonligaPersson/DD2480_Group_27_CI#14]
Exactly what information can you get from the webhook service? Is it possible to extract the code through the webhook?

**Comment by PersonligaPersson** [comment]
In order to extract the code from github for our own CI-server we are going to have to write code that uses github's REST-API to fetch the code. This means that we're going to subscribe to the pull-request event in the webhook service and then make a call to the CI-server which in turn calls githubs API.

**Comment by PersonligaPersson** [comment]
We have decided to use the github checkout functionality to fetch the code. This means that we don't have to use the rest api for that task.

**Comment by BastienFaivre** [comment]
I'll implement this using the information given in the webhook

**Comment by BastienFaivre** [comment]
This issue is now closed
