### ISSUE TITLE
Project Structure

### ISSUE THREAD

**Issue by mellonnen** [PersonligaPersson/DD2480_Group_27_CI#7]
Setup a project solid project structure for a CI server in python.

## Proposal
I propose something like this ([inspiration](https://www.delftstack.com/howto/python/python-project-structure/#an-example))
```
DD2480_Group_27_CI/
├── README.md
├── requirements.txt
├── run.py
├── ci_server
│   ├── __init__.py
│   ├── server.py
│   └── ...
├── tests
│   └── ci_server
│       ├── test.py
│       └── ...
├── static
│   └── ci_server
│       ├── index.html
│       └── ...
├── past_builds
|       ├── build0.json
│       └── ...
└── venv
    └── ...
```

In this structure, we would implement the server as a standalone module which we would then import into the top level of the project (`run.py`). Most probably we would implement the server as a class inheriting the methods from [BaseHTTPRequerstHandler](https://docs.python.org/3/library/http.server.html#http.server.BaseHTTPRequestHandler) where we simply need to implement the `do_POST` method for the CI actions, and the `do_GET` if we want to serve some HTML or the log file as JSON.

### Some clarifications:
- `requirements.txt`: Manifest file for dependency management through `pip`
- `run.py`: Entrypoint to our program.
- `ci_server/`: module for the server we are implementing.
- `tests/`: The test-suite.
- `static/`: Here we can have static content that we might want to serve, like an `index.html` file as a landing page.
- `venv/`: Virtual environment.

What are your takes on a structure like this? Feel free to come with suggestions! 😁

--- 
EDIT: added a **past_builds** at the top level where log files are placed ([see amandas feedback](https://github.com/PersonligaPersson/DD2480_Group_27_CI/issues/7#issuecomment-1032745287)) This folder should nu be placed under source control though but I have it marked here for clarity

**Comment by AmandaStromdahl** [comment]
I think it looks well-thought-out. For this structure, would the build history files be placed in /static or in /ci_server?

**Comment by mellonnen** [comment]
Hmm that is interesting, probably we would want it at the top level of the project in some way (not I `ci_server/` as it is the library code), but is not certain that having it in `static/` makes sense as build files would be added into it all the time. Perhaps we could have a `builds` folder at the top level where we place the different log files for the builds. 

Another alternative that the server has an option for configuring where to place the logs? I think this makes sense as the logs should not under source control in any case, rather they are artifacts generated by the program

**Comment by AmandaStromdahl** [comment]
I agree that your second alternative sounds like a nicer solution, but I think placing the build history in a static folder, e.g. one named ***/past_builds***, would be easiest and would suffice for this project.

**Comment by AmandaStromdahl** [comment]
I meant we could place them in ***/DD2480_Group_27_CI/past_builds***, a.ka. in the top level as you suggested in your first alternative.

**Comment by mellonnen** [comment]
Ok gotcha! Think that will suffice!

**Comment by mellonnen** [comment]
I will make a PR for this now and setup a code skeleton much like @BastienFaivre did in #19 and a code skeleton using PyTest as it seems to be the best option (see #17)
